version: '3.2'
services:
  mysql:
    image: library/mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: tech
      MYSQL_DATABASE: tech

  php_build:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/app
    command: composer install

  php:
    build:
      context: ./docker/php
    links:
      - mysql
    volumes:
      - .:/var/www/app
    depends_on:
      - mysql
      - php_build
    command:
      - 'php-fpm'
    environment:
      APP_ENV: dev
      API_URL: http://localhost/api
      DATABASE_URL: "mysql://root:tech@mysql/tech"

  nginx:
    image: library/nginx:latest
    ports:
      - 80:80
    links:
      - php
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
      - ./docker/fastcgi.conf:/etc/nginx/fastcgi.conf
